from enum import Enum

class Jogador(Enum):
    JOGADOR_DE_BRANCAS = 0
    JOGADOR_DE_PRETAS = 1

class StatusDeFimDeJogo(Enum):
    CHEQUE_MATE = "DERROTA"
    DESISTENCIA = "DERROTA"
    AFOGAMENTO = "EMPATE"
    EMPATE_ACEITO = "EMPATE"
    CHEQUE = "NEUTRO"

class TipoDeMovimento(Enum):
    PEAO = 0
    UNICO = 1
    INFINITO = 2

class TipoDeCordenadaInvalida(Enum):
    CORDENADAS_DE_TAMANHO_INVALIDO = 0
    CORDENADAS_DE_FORMATO_INVÁLIDO = 1
    CORDENADAS_NAO_APONTAM_PARA_PECA = 2
    CORDENADAS_NAO_APONTAM_PARA_SUA_PECA = 3
    CORDENADAS_NAO_APONTAM_PARA_MOVIMENTO_POSSIVEL = 4
    CORDENADAS_INVALIDAS = 5